### Iris = زنبق

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
print(dir(data))

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [4]:
df = pd.DataFrame(data.data, columns= data.feature_names)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [6]:
X, y = data.data, data.target

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [8]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
acc = model.score(X_test, y_test)
print(acc)

1.0


In [9]:
model.predict([X_test[0]])

array([1])

In [10]:
model.coef_

array([[-0.4173221 ,  0.96066887, -2.40901038, -1.00881416],
       [ 0.48966708, -0.18183282, -0.20133576, -0.8176245 ],
       [-0.07234499, -0.77883605,  2.61034614,  1.82643866]])

In [11]:
X_test[0]

array([6.3, 2.5, 4.9, 1.5])

In [12]:
model.intercept_

array([  9.32022185,   1.87705655, -11.1972784 ])

In [13]:
result_list = [np.dot(model.coef_[i], X[0]) + model.intercept_[i] for i in range(3)]
print(result_list)

[6.979842820769974, 3.292548850123535, -10.272391670893553]


In [14]:
results = [0]*3
for i in range(3):
    for j in range(4):
        results[i]+=model.coef_[i][j]*X_test[0][j]
    results[i]+=model.intercept_[i]
print(results)

[-4.224607322493965, 2.2943951673494682, 1.9302121551444067]


In [15]:
eulers = [np.e**i for i in result_list]
sum_euler = sum(eulers)
print(sum_euler)

1101.6608293670351


In [16]:
prob = [i/sum_euler for i in eulers]
print(prob)
print(prob.index(max(prob)))

[0.9755719698679036, 0.0244279987480401, 3.1384056244879815e-08]
0


In [17]:
model.predict([X_test[0]])

array([1])