### Iris = زنبق

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
print(dir(data))

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [4]:
df = pd.DataFrame(data.data, columns= data.feature_names)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [6]:
X, y = data.data, data.target

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

In [8]:
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
acc = model.score(X_test, y_test)
print(acc)

0.9333333333333333


In [9]:
predictions = model.predict(X_test)
correct = sum([1 if y==_y else 0 for y, _y in zip(y_test, predictions)])
print(correct)
print(correct/len(predictions))

42
0.9333333333333333


In [10]:
model.predict([X_test[0]])

array([1])

In [11]:
model.coef_

array([[-0.45745385,  0.82308704, -2.31344089, -0.98424398],
       [ 0.50937705, -0.22432676, -0.18841994, -0.81164561],
       [-0.05192321, -0.59876028,  2.50186083,  1.79588959]])

In [12]:
X_test[0]

array([6.3, 2.5, 4.9, 1.5])

In [13]:
model.intercept_

array([  9.63553224,   1.77023669, -11.40576893])

In [14]:
result_list = [np.dot(model.coef_[i], X_test[0]) + model.intercept_[i] for i in range(3)]
print(result_list)

[-4.000935724380103, 2.2777690840995843, 1.72316664028037]


In [15]:
results = [0]*3
for i in range(3):
    for j in range(4):
        results[i]+=model.coef_[i][j]*X_test[0][j]
    results[i]+=model.intercept_[i]
print(results)

[-4.0009357243801045, 2.2777690840995843, 1.72316664028037]


In [16]:
eulers = [np.e**i for i in result_list]
sum_euler = sum(eulers)
print(sum_euler)

15.375432963757255


In [17]:
prob = [i/sum_euler for i in eulers]
print(prob)
print(prob.index(max(prob)))

[0.0011901133813874381, 0.6344467691974341, 0.36436311742117844]
1


In [18]:
model.predict([X_test[0]])

array([1])